In [2]:
#creating arrays
import numpy as np
a = np.array([1,2,3,4])
b = np.arange(10)
print(a)
print(b)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
#to check efficiency of numpy
import numpy as np
a = range(1000)
b = np.arange(1000)
%timeit [i**2 for i in a]
print()
%timeit b**2


165 µs ± 567 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

1.19 µs ± 7.26 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
#How to create arrays using different method
import numpy as np
a = np.array([1,2,3,4])
b = np.arange(10) #10 isn't included
c = np.arange(0,20,2)  #(start, end(Exclusive, step size))
d = np.linspace (0, 2, 5) #start, end (inclusive), number of points
print("Using lists   ",a,"\n")
print("Using np.array   ",b,"\n")
print("Using arange ",c,"\n")
print("Using linspace \n",d,"\n")

Using lists    [1 2 3 4] 

Using np.array    [0 1 2 3 4 5 6 7 8 9] 

Using arange  [ 0  2  4  6  8 10 12 14 16 18] 

Using linspace 
 [0.  0.5 1.  1.5 2. ] 



In [23]:
#dimension, shape and length
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Dimensions of a-array   ",a.ndim)
print("Dimensions of b-array   ",b.ndim)
print("Dimensions of c-array   ",c.ndim)
print("Shape of   ",a.ndim)
print("Dimensions of b-array   ",b.ndim)
print("Dimensions of c-array   ",c.ndim)

Dimensions of a-array    1
Dimensions of b-array    2
Dimensions of c-array    3


In [31]:
#dimension, shape and length
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Dimensions of a-array   ",a.ndim)   
print("Dimensions of b-array   ",b.ndim)   
print("Dimensions of c-array   ",c.ndim)   
print("Shape of a-array ",a.shape)
print("Shape of b-array ",b.shape)   #it print out (row, column)
print("Shape of c-array ",c.shape)   #it print out (row, column, height)
print("length of a-array ",len(a)#it print out no of elements in case of 1-D
print("length of b-array ",len(b))#it print out no of rows in case of 2-D
print("length of c-array ",len(c))#it print out no of rows in case of 3-D

Dimensions of a-array    1
Dimensions of b-array    2
Dimensions of c-array    3
Shape of a-array  (4,)
Shape of b-array  (2, 3)
Shape of c-array  (2, 2, 2)
length of a-array  4
length of b-array  2
length of c-array  2


In [46]:
#creating special arrays
b = np.ones((2,3))
print(b)



[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
d = np.zeros((2,3))
print(d)


[[0. 0. 0.]
 [0. 0. 0.]]


In [51]:
#identitiy array
e = np.eye(4)
d = np.eye(2,3)
print(e)
print()
print(d)



[1. 1. 1. 1.]

[[1. 0. 0.]
 [0. 1. 0.]]


In [53]:
#diagonal array
f = np.diag([1,2,3,4])
diag_elements = np.diag(f) #return the diagonal elmnts of the array
print(f)
print()
print(diag_elements)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[1 2 3 4]


In [1]:
#Creating random numbers arrays
import numpy as np
a = np.random.rand(5)
b = np.random.rand(2,3) #2D array of uniform distribution random numbers
print(a)
print()
print(b)

[0.15365479 0.36070813 0.42241824 0.96394653 0.43336546]

[[0.96682424 0.13655995 0.11048386]
 [0.49773706 0.55793834 0.26091897]]


In [2]:
c = np.random.randn(4)
d = np.random.randn(3,3) #2D array of guassian random numbers
print(c)
print()
print(d)

[-0.00684324  0.06781663  1.40637006  1.50353703]

[[ 0.19506548 -0.60402477  0.3272172 ]
 [-1.12816072 -1.38094106  1.19736387]
 [ 1.25029772  1.0402309  -1.3812634 ]]


In [3]:
#data types
a = np.arange(10)
a.dtype

dtype('int32')

In [4]:
b = np.arange(10, dtype = 'int64')
b.dtype

dtype('int64')

In [5]:
c = np.arange(5, dtype = 'float64')
d = np.zeros(5)
e = np.zeros(4)
print("data type of c", c.dtype)
print("data type of d", d.dtype)
print("data type of e", e.dtype)



data type of c float64
data type of d float64
data type of e float64


In [8]:
f = np.array((2 + 3j, 6+7j, 9+4j))
f.dtype

dtype('complex128')

In [27]:
strings = np.array(['Monday','Tue','Wedneday'])
strings.dtype

dtype('<U8')

In [23]:
bool_array = np.array([True, False, False, True, True,])
bool_array.dtype

dtype('bool')

In [30]:
#indexing 
a = np.arange(12)
print(a[4])
print(a[3:])


4
[ 3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2  1  0]
[ 2  4  6  8 10]


In [37]:
#slicing
a = np.random.rand(2,3)
print(a)
print()
print(a[1,2])
a[1,2] = 20.3564367
print(a)

[[0.27342219 0.9776792  0.81353116]
 [0.1623926  0.0496201  0.14764679]]

0.14764679003892633
[[ 0.27342219  0.9776792   0.81353116]
 [ 0.1623926   0.0496201  20.3564367 ]]


In [39]:
a = np.arange(10)
print(a)
print(a[::-1])
print(a[2:11:2])


[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


In [42]:
a = np.arange(0,15)
print(a)
b = np.arange(0,8)
a [7:] = b[::-1]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5 6 7 6 5 4 3 2 1 0]


In [47]:
#copy and view
a = np.arange(11)
print(a)
b = a[::2] #creating view
print(b)
b[4] = 9999 #even though we modified b, but a is also modified
print("\na after b modication",a)
print("\na after b modication",b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]

a after b modication [   0    1    2    3    4    5    6    7 9999    9   10]

a after b modication [   0    2    4    6 9999   10]


In [48]:
#Checking if they are sharing the same memory 
a = np.arange(11)
b = a[::2] #creating view
print(np.shares_memory(a,b))

True


In [54]:
#creating copy
a = np.arange(11)
b = a.copy()
print("Share memory?? ",np.shares_memory(a, b))
print()
b[5] = 77777
print(a)
print("\na after b modication\n", a)
print("\nb after b modication\n", b)

Share memory??  False

[ 0  1  2  3  4  5  6  7  8  9 10]

a after b modication
 [ 0  1  2  3  4  5  6  7  8  9 10]

b after b modication
 [    0     1     2     3     4 77777     6     7     8     9    10]


In [63]:
#fancy indexing
#important--> it creates copies not views
#boolian mask
a = np.random.randint(1,40,15)
bool_mask = (a % 2 ==0)
extract_from_a = a [bool_mask]
print(extract_from_a)
a[bool_mask] = 0
print(a)

[28 18  4 22 16 30 26 38]
[ 3  0 39 17  0  0  0  0 21 23  0 37  0 17  0]


In [71]:
#integer mask
a = np.arange(51,65)
print(a)
print(a[[2,3,2,4,2,5,2]])
a[[5,9,8]] = -2
print("After masking operation", a)

[51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[53 54 53 55 53 56 53]
After masking operation [51 52 53 54 55 -2 57 58 -2 -2 61 62 63 64]
