In [19]:
import numpy as np
a = np.arange(5)
print("a-array  ",a)
b = a + 1
print("b-array  ",b)
print("a**2  ",a**2)

a-array   [0 1 2 3 4]
b-array   [1 2 3 4 5]
a**2   [ 0  1  4  9 16]


In [18]:
#elements wise multiplication
print("a*b  ", a*b)
print("a-b  ", b-a)


a*b   [ 0  2  6 12 20]
a-b   [1 1 1 1 1]


In [33]:
c = np.diag([1,2,3])
d = np.diag([1,2,3])
print(c,"\n",d)

[[1 0 0]
 [0 2 0]
 [0 0 3]] 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [35]:
print(c*d)
print(c.dot(d))

[[1 0 0]
 [0 4 0]
 [0 0 9]]
[[1 0 0]
 [0 4 0]
 [0 0 9]]


In [32]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a)
print(b)

print(a.dot(b))

[1 2 3]
[1 2 3]
14


In [44]:
#comparison
a = np.array([1,2,3,4])
b = np.array([0,2,1,4])
print(a == b)
print(a > b)


[False  True False  True]
[ True False  True False]


In [46]:
a = np.array([1,2,3,4])
b = np.array([0,2,1])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


In [49]:
#logical operations
a = np.array([1,0,1,0,0,1],dtype = 'bool')
b = np.array([0,1,0,0,1,0],dtype = 'bool')
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False  True  True]
[False False False False False False]


In [51]:
#transcendental operation
a = np.random.randint(4,26, 8)
print(np.sin(a))

[-0.95892427 -0.13235175 -0.28790332  0.83665564 -0.7568025   0.83665564
 -0.2794155   0.14987721]


In [52]:
a = np.random.randint(2,12,7)
print(np.log(a))

[2.30258509 0.69314718 1.38629436 1.60943791 2.07944154 2.07944154
 2.39789527]


In [53]:
a = np.random.randint(1,5,4)
print(np.exp(a))

[ 7.3890561  20.08553692 54.59815003 54.59815003]


In [57]:
#Reduction operation
a = np.random.randint(2,21,7)
print("a-array    ", a)
print("Summation of a-array ", a.sum())
print("minimum of a-array ", a.min())
print("maximum of a-array ", a.max())
print("index of minimum of a-array ", a.argmin())
print("index of maximum of a-array  ", a.argmax())

a-array     [15 16  2 18 14  8  6]
Summation of a-array  79
minimum of a-array  2
maximum of a-array  18
index of minimum of a-array  2
index of maximum of a-array   3


In [70]:
#summation
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.sum(axis = 1))   #row wise summation
print(a.sum(axis = 0))   # column wise summation


[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]


In [82]:
#logical
a = np.array([0,2,3,4])
b = np.array([0,0,0,0])
print(np.any(b > a))
print(np.any(b >= a))
print(np.all(b >= a))

zeross = np.zeros((50,50))

print(np.any(zeross != 0))
print(np.all(zeross == 0))


False
True
False
False
True


In [86]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
c = np.array([5,6,7,8])
((b >= a) & (c >= a)).all()

True

In [87]:
a = np.array([1,2,3,4])
print(a.all())

True


In [107]:
#statistics
a = np.random.randint(5,20,8)
print(sorted(a))
print(a.mean())
print(np.median(a))

[5, 7, 10, 11, 12, 12, 14, 17]
11.0
11.5


In [114]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(np.median(a, axis = 1)) #row wise
print(np.median(a, axis = 0)) #column wise
print(a.mean(axis = 1))      #row wise
print(a.mean(axis = 0))     #column wise
print("Standard deviation  ", a.std())

[3. 7.]
[3.5 4.5 5.5 6.5 2.5]
[3. 6.]
[3.5 4.5 5.5 6.5 2.5]
Standard deviation   2.8722813232690143


In [3]:
data = np.loadtxt("populations.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [5]:
year, hare, Lynx, carrots = data.T
print(year)

[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


In [6]:
population = data[:,1:]
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [8]:
print("Column wise std",population.std(axis = 0))

Column wise std [20897.90645809 16254.59153691  3322.50622558]


In [14]:
print("row wise std",np.argmax(population, axis = 1))

row wise std [2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2]
