In [10]:
#Broadcasting
import numpy as np
a = np.arange(0,40,10)
a_updated = np.tile(a, (3,1))
new_a = a_updated.T
print(new_a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [15]:
b = np.array([1, 2, 3])
new_a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [17]:
b = np.array([11, 22, 33, 44])
a_updated + b

array([[11, 32, 53, 74],
       [11, 32, 53, 74],
       [11, 32, 53, 74]])

In [19]:
a = np.arange(0,40,10)
print(np.tile(a, (3,2)))


[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [29]:
a = np.arange(0,40,10)
update_a = a[:,np.newaxis] #Convert it to 2D array
print("shape  ", update_a.shape,"\n")
print(update_a)

shape   (4, 1) 

[[ 0]
 [10]
 [20]
 [30]]


In [23]:
b = np.array([1,2,3])
update_a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [10]:
#Flatening and reshaping
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = a.ravel()
print(b)
c = b.reshape(3,2)
print(c)
c[2][0] = 99
print("a\n",a)
print("b\n",b)
print("c\n",c)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
a
 [[ 1  2  3]
 [ 4 99  6]]
b
 [ 1  2  3  4 99  6]
c
 [[ 1  2]
 [ 3  4]
 [99  6]]


In [18]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
print(a)
print(b)
b[0] = 33
print(a)
print(b)



[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[33.  0.  0.  0.  0.  0.]


In [19]:
a = np.zeros((3,2))
print(a)
b = a.T.reshape(2,3)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
z = np.array([1, 2, 3, 4])
z[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [21]:
print(z)

[1 2 3 4]


In [25]:
a = np.arange(4*3*2)
b = a.reshape(4,3,2)
print(b)
print("*****************")
print(b[2][2][1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
*****************
17


In [33]:
a = np.array([1,2,3,4])
a.resize((8,))
print(a)

[1 2 3 4 0 0 0 0]


In [34]:
a = np.array([1,2,3,4])
b = a
a.resize((8,))
print(a)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [47]:
a =np.random.randint(0,10,20)
b = a.reshape(4,5)
print(b)
c = np.sort(b, axis = 1)
print ("\nAfter row wise sorting \n\n", c)
d = np.sort(b, axis = 0)
print ("\nAfter column wise sorting \n\n", d)


[[8 9 9 1 2]
 [9 6 1 3 0]
 [8 6 9 3 3]
 [6 9 8 3 6]]

After row wise sorting 

 [[1 2 8 9 9]
 [0 1 3 6 9]
 [3 3 6 8 9]
 [3 6 6 8 9]]

After column wise sorting 

 [[6 6 1 1 0]
 [8 6 8 3 2]
 [8 9 9 3 3]
 [9 9 9 3 6]]


In [49]:
a =np.random.randint(0,10,20)
print(a)
d = np.argsort(a, )
print(a)

[[8 9 9 1 2]
 [9 6 1 3 0]
 [8 6 9 3 3]
 [6 9 8 3 6]]


In [3]:
#Creating matrix with predeficd values
import numpy as np
a = np.full((3,4),(2))
print (a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [4]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
a = np.random.normal(0,1,(3,3))
print(a)

[[-0.56689209  0.18833985  0.72659445]
 [ 0.15256195  1.14303677  0.50151521]
 [-0.19268127  1.36731624 -1.71226007]]


In [25]:
#set a random seed
np.random.seed(0)
a = np.random.randint(8)
b = np.random.randint(8, size = (2,4))
print(a)
print(b)
print()
c = np.random.randint(99, size = (3,5,3))
print(c)
print(c[2,4,2])

4
[[7 5 0 3]
 [3 3 7 1]]

[[[83 21 36]
  [87 70 88]
  [88 12 58]
  [65 39 87]
  [46 88 81]]

 [[37 25 77]
  [72  9 20]
  [80 69 79]
  [47 64 82]
  [88 49 29]]

 [[19 19 14]
  [39 32 65]
  [ 9 57 32]
  [31 74 23]
  [35 75 55]]]
55


In [35]:
#using Concatenation
a = np.arange(10)
b = np.arange(11,20)
c = np.array([-1,-2,-3]) 
d = np.concatenate([a,b,c])
print(d)

[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19 -1 -2 -3]


In [38]:
#using Concatenation to creat nD arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[0,3,6]])
e = np.concatenate(([a,b]), axis = 0) #column wise concatenation 
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 3 6]]


In [39]:
#using Concatenation to creat nD arrays
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[0,3,6]])
e = np.concatenate(([a,b]), axis = 1) #row wise concatenation 
print(e)

[[1 2 3 7 8 9]
 [4 5 6 0 3 6]]


In [60]:
z = np.array([[9],[9]])
grid = np.array([[1,2,3],[17,18,19]])
np.hstack([z,grid])                   #horizental stack

array([[ 9,  1,  2,  3],
       [ 9, 17, 18, 19]])

In [56]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])                         #vertical stack

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [63]:
#spliting based on position (indices)
a = np.arange(10)
new1, new2 = np.split(a,[5])
print(new1)
print(new2)

[0 1 2 3 4]
[5 6 7 8 9]


In [75]:
a = np.arange(16).reshape(4,4)
new1, new2 = np.split(a,[2])
print(new1)
print()
print(new2)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [77]:
np.full((3,3), True, dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
a = np.arange(10)
a[a % 2 ==0]

array([0, 2, 4, 6, 8])

In [86]:
a = np.arange(10)
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [93]:
a = np.arange(10)
new = np.where(a % 2 == 1, -1, a)
print(new)
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [96]:
a = np.arange(10)
a.reshape(2,-1)

ValueError: cannot reshape array of size 10 into shape (2,)

In [97]:
a = np.arange(5)
b = np.arange(5,10)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
a = np.array([1,2,3])
b = np.hstack([a,a,a])
c= np.vstack([a,a,a]).T
c.ravel()
np.concatenate([c.ravel(), b])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [112]:
a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [113]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [114]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [130]:
arr1 = np.random.randint(1,8,15)
arr2 = np.random.randint(1,8,13)
print(arr1)
print(arr2)
np.intersect1d(arr1, arr2)

[6 7 6 2 2 3 1 4 2 5 4 2 2 3 1]
[7 1 3 5 7 1 5 4 4 1 1 4 6]


array([1, 3, 4, 5, 6, 7])

In [154]:
arr1 = np.random.randint(1,12,15)
arr2 = np.random.randint(1,8,15)
print(arr1)
print(arr2)
np.setdiff1d(arr1, arr2)

[ 9  2  6  8  1 11  2 11  4 10  3  9  3  5  9]
[3 2 1 3 4 5 1 3 4 5 4 6 7 1 3]


array([ 8,  9, 10, 11])

In [156]:
pos = np.where(arr1 == arr2)
print(arr1[pos])
print(arr2[pos])

[2 4]
[2 4]


In [175]:
a = np.random.randint(1,10, 15)

unique_values, indices, counts =  unique_values = np.unique(a, return_index = True, return_counts = True)
print(unique_values)
print(indices)
print(counts)


(array([1, 2, 3, 4, 5, 6, 7, 9]), array([13,  6,  0,  1,  4,  3, 11,  2], dtype=int64), array([1, 1, 2, 1, 2, 4, 1, 3], dtype=int64))
[13  6  0  1  4  3 11  2]
[1 1 2 1 2 4 1 3]


In [174]:
a?